### ISSUE TITLE
能否添加自动更新？

### ISSUE THREAD

**Issue by Fununugugu** [ZGIT-Network/OpenFrpLauncher#1]
如题，好像您的软件只能在启动的时候检查一次更新，使用过程中并不会检查更新，这会导致所有的隧道失灵

**Comment by Yue-cn** [comment]
好的，不过隧道失灵是怎么一个表现呢？可以详细说说吗

**Comment by Yue-cn** [comment]
启动器可更新(FRPC本来就可以): https://github.com/ZGIT-Network/OpenFrpLauncher/commit/331a1264dbfb9912b2832f3ee06e5318d6e9640a

**Comment by Yue-cn** [comment]
finish. https://github.com/ZGIT-Network/OpenFrpLauncher/commit/ed5bfbca67a7e5041cbd5022ca10860b048956f9
