### ISSUE TITLE
[Bug] 无法在客户端内新建HTTP(S)隧道

### ISSUE THREAD

**Issue by LxHTT** [ZGIT-Network/OpenFrpLauncher#2]
如题，客户端没有给创建此类隧道时可填写绑定域名等信息的区域，导致无法创建隧道，而使客户端提示：  
` 上传失败 后台出现异常，请重试或联系管理员处理 `  
客户端版本Preview 21

**Comment by Yue-cn** [comment]
完，是我压根没做选项

**Comment by Yue-cn** [comment]
Finish.
https://github.com/ZGIT-Network/OpenFrpLauncher/commit/77db4517f790fb87bee0cf2d8b44062c09ee7372
