### ISSUE TITLE
首页内容不更新

### ISSUE THREAD

**Issue by xiaoxing365** [ZGIT-Network/OpenFrpLauncher#6]
首页内容不更新，签到界面要加载好长时间，而且，在网页端签了到，客户端的首页中可用流量不更新。
再者，不管是在网页端还是在客户端创建了隧道，主页中的隧道也不会更新（点了更新中的刷新也一样），设置中的也不更新

希望：日志别只输出通道是否有已打通、未打通、丢失连接、重新链接等，把用户的连接IP、通道已连接的数量也加上

还有个不知道是节点的问题还是客户端的问题：河北电信2节点每过几分钟就要重新连接一次

**Comment by xiaoxing365** [comment]
补充一点，能不能搞个自动登录啊，每次打开都得重新登录

**Comment by Yue-cn** [comment]
自动登录问题修了，那个是保存配置文件的问题（其实是直接关机）。现在可以直接关机了，会保存文件的；
https://github.com/ZGIT-Network/OpenFrpLauncher/commit/11cb9e2ad79e2073189832e27252949ace0ffa46

**Comment by Yue-cn** [comment]
网页端签到并不代表立即刷新（数据不可能实时），需要您点击首页“右上角”头像进行刷新

**Comment by Yue-cn** [comment]
> 还有个不知道是节点的问题还是客户端的问题：河北电信2节点每过几分钟就要重新连接一次

这个是您与节点之间的链接问题，也即是跟客户都无关；

> 希望：日志别只输出通道是否有已打通、未打通、丢失连接、重新链接等，把用户的连接IP、通道已连接的数量也加上

这个是 FRPC 的事，可惜我不能干涉（因为我只是写启动器的）
